# In your generated migration_script.py

from alembic import op
import sqlalchemy as sa

# ... other migration details ...

def upgrade():
    # Instead of autogenerated op.create_table('message_fts', ...)
    op.execute("""
        CREATE VIRTUAL TABLE IF NOT EXISTS message_fts USING fts5(
            content,
            content_table='messages',
            content_rowid='id'
        )
    """)
    op.execute("""
        CREATE TRIGGER IF NOT EXISTS messages_ai_trigger
        AFTER INSERT ON messages
        BEGIN
            INSERT INTO message_fts (rowid, content)
            VALUES (new.id, new.content);
        END;
    """)
    # ... similar op.execute() for note_fts, file_fts, and all other triggers ...

def downgrade():
    op.execute("DROP TRIGGER IF EXISTS messages_ai_trigger")
    # ... drop other triggers ...
    op.execute("DROP TABLE IF EXISTS message_fts")
    # ... drop other FTS tables ...
