"""add todo_items table

Revision ID: 4c094b25891b
Revises: 8a3d29562348
Create Date: 2025-05-18 19:36:17.790670

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c094b25891b'
down_revision = '8a3d29562348'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('todo_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_todo_items'))
    )
    # Removed incorrect drop_table operations for FTS tables
    with op.batch_alter_table('file_fts', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('rowid', sa.Integer(), nullable=False)) # Incorrect for FTS
        pass # No changes needed for file_fts structure by Alembic

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_files_filename'), ['filename'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_uploaded_at'), ['uploaded_at'], unique=False)

    with op.batch_alter_table('message_fts', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('rowid', sa.Integer(), nullable=False)) # Incorrect for FTS
        pass # No changes needed for message_fts structure by Alembic

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('note_fts', schema=None) as batch_op:
        # batch_op.add_column(sa.Column('rowid', sa.Integer(), nullable=False)) # Incorrect for FTS
        pass # No changes needed for note_fts structure by Alembic

    with op.batch_alter_table('note_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note_history_note_id'), ['note_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_note_history_saved_at'), ['saved_at'], unique=False)

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notes_last_saved_at'), ['last_saved_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_last_saved_at'))

    with op.batch_alter_table('note_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_history_saved_at'))
        batch_op.drop_index(batch_op.f('ix_note_history_note_id'))

    with op.batch_alter_table('note_fts', schema=None) as batch_op:
        # batch_op.drop_column('rowid') # Incorrect for FTS
        pass # No changes needed for note_fts structure by Alembic

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_timestamp'))
        batch_op.drop_index(batch_op.f('ix_messages_chat_id'))

    with op.batch_alter_table('message_fts', schema=None) as batch_op:
        # batch_op.drop_column('rowid') # Incorrect for FTS
        pass # No changes needed for message_fts structure by Alembic

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_files_uploaded_at'))
        batch_op.drop_index(batch_op.f('ix_files_filename'))

    with op.batch_alter_table('file_fts', schema=None) as batch_op:
        # batch_op.drop_column('rowid') # Incorrect for FTS
        pass # No changes needed for file_fts structure by Alembic

    # Removed incorrect create_table operations for FTS tables
    # op.create_table('message_fts_idx', # Removed
    # All the FTS related op.create_table calls and their sa.Column definitions are removed here.
    op.drop_table('todo_items')
    # ### end Alembic commands ###
