"""Add note history table

Revision ID: 4e80e8b93441
Revises: b39695d5f072
Create Date: 2025-04-22 16:10:55.799291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e80e8b93441'
down_revision = 'b39695d5f072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('note_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('note_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('saved_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['note_id'], ['notes.id'], name=op.f('fk_note_history_note_id_notes'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_note_history'))
    )
    with op.batch_alter_table('note_history', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_note_history_note_id'), ['note_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_note_history_saved_at'), ['saved_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note_history', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_note_history_saved_at'))
        batch_op.drop_index(batch_op.f('ix_note_history_note_id'))

    op.drop_table('note_history')
    # ### end Alembic commands ###
