"""add_fts_and_triggers

Revision ID: 8a3d29562348
Revises: f9f87a845197
Create Date: 2025-05-08 09:52:51.875710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a3d29562348'
down_revision = 'f9f87a845197'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_fts',
    sa.Column('rowid', sa.Integer(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('rowid', name=op.f('pk_file_fts'))
    )
    op.create_table('message_fts',
    sa.Column('rowid', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('rowid', name=op.f('pk_message_fts'))
    )
    op.create_table('note_fts',
    sa.Column('rowid', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('rowid', name=op.f('pk_note_fts'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('note_fts')
    op.drop_table('message_fts')
    op.drop_table('file_fts')
    # ### end Alembic commands ###
