"""Initial migration based on existing models

Revision ID: b18b2c0ee191
Revises: 
Create Date: 2025-04-22 15:38:38.569767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b18b2c0ee191'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=150),
               existing_nullable=False,
               existing_server_default=sa.text("'New Chat'"))
        batch_op.alter_column('model_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False,
               existing_server_default=sa.text("'gemini-2.0-flash'"))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('last_updated_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index('idx_chats_last_updated')

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('filename',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('mimetype',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('uploaded_at',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index('idx_files_filename')
        batch_op.drop_index('idx_files_uploaded_at')
        batch_op.create_index(batch_op.f('ix_files_filename'), ['filename'], unique=False)
        batch_op.create_index(batch_op.f('ix_files_uploaded_at'), ['uploaded_at'], unique=False)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.drop_index('idx_messages_chat_id')
        batch_op.drop_index('idx_messages_timestamp')
        batch_op.create_index(batch_op.f('ix_messages_chat_id'), ['chat_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_timestamp'), ['timestamp'], unique=False)

    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=150),
               existing_nullable=False,
               existing_server_default=sa.text("'New Note'"))
        batch_op.drop_index('idx_notes_last_saved')
        batch_op.create_index(batch_op.f('ix_notes_last_saved_at'), ['last_saved_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notes_last_saved_at'))
        batch_op.create_index('idx_notes_last_saved', ['last_saved_at'], unique=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'New Note'"))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_timestamp'))
        batch_op.drop_index(batch_op.f('ix_messages_chat_id'))
        batch_op.create_index('idx_messages_timestamp', ['timestamp'], unique=False)
        batch_op.create_index('idx_messages_chat_id', ['chat_id'], unique=False)
        batch_op.alter_column('timestamp',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('role',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_files_uploaded_at'))
        batch_op.drop_index(batch_op.f('ix_files_filename'))
        batch_op.create_index('idx_files_uploaded_at', ['uploaded_at'], unique=False)
        batch_op.create_index('idx_files_filename', ['filename'], unique=False)
        batch_op.alter_column('uploaded_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('mimetype',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('filename',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.create_index('idx_chats_last_updated', ['last_updated_at'], unique=False)
        batch_op.alter_column('last_updated_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('model_name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'gemini-2.0-flash'"))
        batch_op.alter_column('name',
               existing_type=sa.String(length=150),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'New Chat'"))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
