"""Add note_diff column to note_history

Revision ID: ea9779eb17cf
Revises: 4e80e8b93441
Create Date: 2025-04-24 08:54:12.720858

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea9779eb17cf'
down_revision = '4e80e8b93441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note_diff', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note_history', schema=None) as batch_op:
        batch_op.drop_column('note_diff')

    # ### end Alembic commands ###
